name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Run doctl build command
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
        id: go
      - name: Run Go tests
        run: go test -v ./...

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run doctl apps dev build
        run: doctl apps dev build --no-cache
      
      - name: Start App container in background
        run: docker run -d -e PORT=8080 -p 8080:8080 web:dev

      - name: Wait for App to be ready and test
        run: |
          sleep 5
          curl http://localhost:8080/ping
      
